sonar.projectKey=gabysmm_ReadRats
sonar.organization=gabysmm

sonar.sources=backend
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**

sonar.tests=backend/tests
sonar.python.version=3.12
