name: ReadRats Workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test-secret-key-for-ci
      TEST_USER_PASSWORD: test-user-password
    steps:
      - uses: actions/checkout@v7 #vai pegar o codigo do repositorio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: instalar graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev
      - run: pip install -r backend/requirements.txt
      - name: check deprecated code
        run: |
          cd backend
          pytest -v -W error::DeprecationWarning
      - name: checar padrão de codificação com Ruff
        run: |
           cd backend
           ruff format .
           ruff check . --fix
      - name: detectar código duplicado & Code smells
        run: |
          cd backend
          pylint \
            --disable=all \
            --enable=R0801,C0114,C0115,C0116 \
            --min-similarity-lines=2 \
            --ignore-paths='.*migrations.*' \
            .
      - name: gerar diagrama UML
        run: |
          cd backend
          python manage.py graph_models -a -g -o ../docs/uml.png
      - name: Upload do diagrama UML
        uses: actions/upload-artifact@v4
        with:
          name: uml-diagram
          path: docs/uml.png

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do código
        uses: actions/checkout@v7

      - name: executar OWASP dependency check
        uses: dependency-check/DependencyCheck_Action@main
        id: depcheck
        with:
          project: 'ReadRats'
          format: 'HTML'
          args: |
            --scan ./backend
            --enableExperimental
            --out ./reports

      - name: Fazer upload do relatório de segurança
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
