name: ReadRats Workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 #vai pegar o codigo do repositorio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r backend/requirements.txt
      - name: check deprecated code
        run: |
          cd backend
          pytest -v -W error::DeprecationWarning
      - name: checar padrão de codificação com Ruff
        run: |
           cd backend
           ruff check .
      - name: detectar código duplicado
        run: |
          cd backend
          pylint \
            --disable=all \
            --enable=R0801 \
            --min-similarity-lines=2 \
            --ignore-paths='.*migrations.*' \
            .

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: executar OWASP dependency check
        uses: dependency-check/DependencyCheck_Action@main
        id: depcheck
        with:
          project: 'ReadRats'
          format: 'HTML'
          args: |
            --scan ./backend
            --enableExperimental
            --out ./reports

      - name: Fazer upload do relatório de segurança
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
